### ISSUE TITLE
KeePass on Linux (MONO) password file corruption on google drive

### ISSUE THREAD

**Issue by rjt** [kapitainsky/RcloneBrowser#110] opened 2020-04-26 14:57 UTC
`rclone mount GoogleDrive:KDBX/ ~/GoogleDrive/OurSharedPrivateDrive/KDBX/ --vfs-cache-mode full`

resulted in multiple corrupt password files.  Even when doing a very small edit.

**Comment by kapitainsky** [comment] 2020-04-26 15:11
And it is related to Rclone Browser? Or rclone?

**Comment by rjt** [comment] 2020-04-26 22:08
I would say rclone 1.48.0 because i only pull up rclone browser (1.7.0) sometimes after running the cli.

**Comment by kapitainsky** [comment] 2020-04-26 22:13
Sorry - I am not sure what the issue is. Some files you transferred have been corrupted?

**Closed** 2020-04-27 11:13 UTC
