### ISSUE TITLE
Option to automatically strip .DS_Store files when uploading on Mac

### ISSUE THREAD

**Issue by dia3olik** [kapitainsky/RcloneBrowser#25] opened 2019-10-26 11:05 UTC
Hey man!

firstly I wanted to thank you for picking up the project, it really needed an update and a future!!! ;-)

Back on topic, I think an easy and quick option (even "on" by default maybe?) to filter out on upload all the .DS_Store files on each directory which MacOs creates would be really really handy for less experienced users since it would be less cumbersome and straightforward than dealing with custom filtering timeline option strings each time ;-)

What do you think?

**Comment by kapitainsky** [comment] 2019-10-26 16:42
Not sure. Any files can be excluded right now in job preferences if somebody wishes. At the same time .DS_Store files are tiny and there is no harm in copying them. Myself when I copy folder I want everything to be included unless I specify otherwise - I don't like silent default exclusion.

**Comment by Alphos2000** [comment] 2019-10-26 22:04
¿And would be possible to save the exclude file list, so you don't have to write it everytime? Maybe a box to activate or desactivate filelist, and it always is stored sou you dont have to write it always.

**Comment by kapitainsky** [comment] 2019-10-27 00:57
I am thinking about adding default extra arguments option in general settings. They would be applied to any new job. It is the most universal and solves many issues including default exclusion list e.g. you could specify in setting "--exclude-from file".

**Comment by dia3olik** [comment] 2019-10-27 10:49
This would be close enough and also universal for various needs, it's a cool idea regardless ;-)
Thanks!!!
But I still think that on the Mac build a simple toggle on/off to exclude all .DS_Store files would be a godsend for speed and to keep things simple, these pesky files are not needed for the kind of files/folders you want to upload to the cloud...and can lead to cleaner folders on the cloud.

**Comment by kapitainsky** [comment] 2019-10-27 11:42
In just released [1.6.0](https://github.com/kapitainsky/RcloneBrowser/releases/tag/1.6.0) I have included default job options. It means that now it is easy to have  "--exclude-from file" by default for every new Upload.

**Comment by kapitainsky** [comment] 2019-10-27 11:58
I will take a note and for the next release I can make for macOS default options for Upload "--exclude .DS_Store" so total new users will have it on from first install. 

Try latest release and let me know if any issues.

**Comment by dia3olik** [comment] 2019-10-27 12:44
Thanks! That was quick!!! ;-)
I totally agree, that would be a very good way indeed.

**Comment by kapitainsky** [comment] 2019-10-29 11:39
Done in commit aa826eb7a59741671bf24ccda349792be3b364ee

Will roll out with the next release. no ETA atm

**Comment by dia3olik** [comment] 2019-11-15 13:54
I just tried on an upload with latest versions (1.6.0 + rclone 1.50.1) and with the default option "--exclude .DS_Store" it still uploads these...strange! what could be the culprit?? thanks!

**Comment by kapitainsky** [comment] 2019-11-15 13:56
can you post screenshot of your job? I tested it myself and it works

**Comment by kapitainsky** [comment] 2019-11-15 13:58
you can also try the next release preview

https://www.icloud.com/iclouddrive/0TXekZ4JL1TAANEGhM3IGReNQ#rclone-browser-1.6.0-409180a-macOS

Final release will probably include more fixes but .DS_Store is already there

**Comment by dia3olik** [comment] 2019-12-11 12:26
Hi! I just tried again with 1.7.0 and it still uploads .DS_Store files...

**Comment by kapitainsky** [comment] 2019-12-11 12:29
have you put "--exclude .DS_Store" in default upload options? It is set for new rclone browser installations on macOS but for existing ones I don't change anything

**Comment by dia3olik** [comment] 2019-12-11 12:30
yes of course but it's ignoring it completely...

**Comment by kapitainsky** [comment] 2019-12-11 12:31
<img width="824" alt="Screenshot 2019-12-11 at 12 30 11 1" src="https://user-images.githubusercontent.com/15635386/70621711-1d03d180-1c12-11ea-9591-6e8fcb019a2c.png">

**Comment by kapitainsky** [comment] 2019-12-11 12:42
Ok. I see where the issue is. Stupid bug.

It works when you save you upload as a task and then run it. When you run it directly options are ignored. Will be fixed. In the meantime go through task step.

**Comment by kapitainsky** [comment] 2019-12-11 13:06
it is strange. As it works now for me. I will have to investigate it more

**Comment by kapitainsky** [comment] 2019-12-11 13:39
I did few tests.... and it works... Could you please try again - just make sure that transfer window had default exclude
<img width="899" alt="Screenshot 2019-12-11 at 13 37 49" src="https://user-images.githubusercontent.com/15635386/70626024-876d3f80-1c1b-11ea-9eed-58913b9f6503.png">

I think in my first test I pressed restore defaults and extra options were cleared... I should change this behaviour as default extras should be one set in preferences.

**Comment by kapitainsky** [comment] 2019-12-11 13:42
You can also clean already uplaoded .DS_Store files by running sync (not copy) and specifying following:

<img width="899" alt="Screenshot 2019-12-11 at 13 27 01" src="https://user-images.githubusercontent.com/15635386/70626268-06fb0e80-1c1c-11ea-88ee-f6c6107564d8.png">

**Comment by dia3olik** [comment] 2019-12-11 13:53
Thanks for the tip, yeah I have the option enabled but it's ignored...

I have the files on a NAS shared with AFP to my Mac on which I have installed RCB.

I'll try to do a screen rec and upload it to show you...in the mean time how can I batch delete all the .DS_Store files on the remote if I don't have the local source directory anymore to sync it from?

Thanks!

**Comment by kapitainsky** [comment] 2019-12-11 14:01
https://rclone.org/commands/rclone_delete/

for this you need cmd rclone. Assuming that your data is stored on remote in /Testing folder

`rclone delete --dry-run --include .DS_Store  remote:/Testing/`

run this with --dry-run first to double check what will be deleted

**Comment by dia3olik** [comment] 2019-12-11 14:02
thanks man!

I'll keep you updated ;-)

BTW it would be nice to implement a selective search&delete feature on RCB ;-)

**Comment by kapitainsky** [comment] 2019-12-11 14:07
I thought about it. Simply I can add delete option... but... I am afraid of power of this command. 

People spend days uploading their stuff to slow remote and then one wrong click and all can be gone. There is always cmd for power users.

**Comment by dia3olik** [comment] 2019-12-11 14:17
you're right but maybe you can implement it with many warnings and maybe with --dry-run as default?

**Comment by kapitainsky** [comment] 2019-12-20 11:01
I have tested on few different macs and when  ‘—exclude .DS_Store‘ is specifies in extra options .DS_Store files are ignored. Maybe you has some typo in extra options? Or still it is reproducible issue?

**Comment by dia3olik** [comment] 2019-12-20 11:06
the default you wrote in the current version is --exclude ".DS_Store" so maybe this is the culprit? If it is please correct it in the next version to be "--exclude .DS_Store”

**Comment by kapitainsky** [comment] 2020-02-17 13:50
It has been fixed in the [latest release](https://github.com/kapitainsky/RcloneBrowser/releases/tag/1.8.0)

**Closed by kapitainsky** 2020-02-17 13:50 UTC
Labels: enhancement, will be fixed in the next relase
